services:
  jekyll:
    build:
      context: .
      args:
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}

    volumes:
      - .:/site

    ports:
      - "4000:4000"
      - "35729:35729"

    environment:
      JEKYLL_ENV: development

